// src/components/Contact.jsx
import { contacts } from '../data/siteData'
import LinkItem from './Link'

function Contact() {
  return (
    <section className="section row end-xs" data-id="5">
      <ul className="list col-xs-12 col-md-9">
        <li>
          {contacts.map((contact, index) => (
            <div key={index} className="social">
              <LinkItem item={contact} />
            </div>
          ))}
        </li>
      </ul>
    </section>
  )
}

export default Contact

// components/Contact.vue
<template>
  <section class="section row end-xs" data-id="5">
    <ul class="list col-xs-12 col-md-9">
      <li>
        <div v-for="(contact, index) in contacts" :key="index" class="social">
          <Link :item="contact" />
        </div>
      </li>
    </ul>
  </section>
</template>

<script>
import Link from '../components/Link'

export default {
  components: {
    Link
  },
  data(context) {
    return {
      contacts: context.$store.state.contacts
    }
  }
}
</script>
