// src/components/Link.jsx
import Arrow from './Arrow'

function LinkItem({ item }) {
  return (
    <a href={item.href} className="text arrow" target="_blank" rel="noreferrer">
      <span className="reveal">
        <span className="item">
          <span className="arrow__label">{item.label}</span>
        </span>
      </span>
      <span className="arrow__icon">
        <Arrow />
      </span>
    </a>
  )
}

export default LinkItem

// components/Link.vue
<template>
  <a :href="item.href" class="text arrow" target="_blank">
    <span class="reveal">
      <span class="item">
        <span class="arrow__label">{{ item.label }}</span>
      </span>
    </span>
    <span class="arrow__icon"><Arrow /></span>
  </a>
</template>

<script>
import Arrow from '../components/Arrow'

export default {
  components: {
    Arrow
  },
  props: {
    item: {
      type: Object,
      default: null
    }
  }
}
</script>
